import type { AgeStage, Recipe } from "./types";

/**
 * Curated, age-staged baby & toddler recipe library.
 *
 * Method steps are written in our own words; ingredient lists are factual.
 * Each recipe links out to a reputable weaning source so you can read the
 * original and full safety guidance. Always follow your paediatrician's advice
 * on introducing allergens and on choking-hazard textures.
 *
 * Age filtering is band-based: a recipe shows only when the selected age falls
 * within [minMonths, maxMonths]. So smooth first-food purées drop off for older
 * babies — a 12-month-old won't be served 6-month purées.
 */

export const STAGES: AgeStage[] = [
  { id: "6m", label: "6 months", short: "6m", minMonths: 6, tone: "mint", blurb: "First tastes — smooth single-ingredient purées & soft steamed sticks." },
  { id: "8m", label: "8 months", short: "8m", minMonths: 8, tone: "butter", blurb: "Mashed combos & easy finger foods as she learns to self-feed." },
  { id: "10m", label: "10 months", short: "10m", minMonths: 10, tone: "peach", blurb: "More texture — soft lumps, mini meals and handheld bites." },
  { id: "12m", label: "12 months", short: "12m", minMonths: 12, tone: "lilac", blurb: "Toddler meals — family food, chopped small. (No more smooth purées.)" },
  { id: "18m", label: "18 months+", short: "18m+", minMonths: 18, tone: "coral", blurb: "Confident eater — bigger flavours and lunchbox ideas." },
];

const SRC = {
  nhs: { name: "NHS Start for Life", url: "https://www.nhs.uk/start-for-life/baby/weaning/recipes-and-meal-ideas/" },
  solidstarts: { name: "Solid Starts", url: "https://solidstarts.com/foods/" },
  bbc: { name: "BBC Good Food", url: "https://www.bbcgoodfood.com/recipes/collection/baby-and-toddler-recipes" },
  karmel: { name: "Annabel Karmel", url: "https://www.annabelkarmel.com/recipes/" },
  hlf: { name: "Healthy Little Foodies", url: "https://www.healthylittlefoodies.com/category/baby/" },
  hhFirstFood: { name: "HealthHub (HPB) — Baby’s First Food Journey", url: "https://www.healthhub.sg/live-healthy/babys_first_food_journey" },
  hhSolids: { name: "HealthHub (HPB) — Getting Ready for Solids", url: "https://www.healthhub.sg/well-being-and-lifestyle/pregnancy-and-infant-health/baby-getting-ready-for-solids" },
  hxWean: { name: "HealthXchange (SingHealth) — When & How to Wean", url: "https://www.healthxchange.sg/health-articles/baby-life-stages/baby-feeding/when-how-wean-baby" },
  hxGrowing: { name: "HealthXchange (SingHealth) — Top 10 Foods for the Growing Child", url: "https://www.healthxchange.sg/children/food-nutrition/foods-growing-child" },
  singhealth612: { name: "SingHealth — Early Childhood Nutrition 6–12 Months", url: "https://polyclinic.singhealth.com.sg/Documents/Early%20childhood%20nutrition%20from%206-12%20months.pdf" },
};

export const RECIPES: Recipe[] = [
  // ---------- 6 months+ ----------
  { id: "avocado-mash", title: "Creamy Avocado Mash", emoji: "🥑", minMonths: 6, maxMonths: 11, prepMins: 5, servings: "1 baby portion", texture: "Smooth mash", tags: ["No-cook", "Healthy fats", "4 ingredients or fewer"], ingredients: ["½ ripe avocado", "1–2 tsp breast milk or formula (to loosen)"], steps: ["Scoop the avocado flesh into a bowl.", "Mash with a fork until very smooth.", "Stir in a little milk to reach a soft, spoonable texture.", "Serve at room temperature straight away."], tip: "Avocado browns fast — make it just before serving.", source: SRC.solidstarts },
  { id: "sweet-potato-puree", title: "Sweet Potato Purée", emoji: "🍠", minMonths: 6, maxMonths: 10, prepMins: 20, servings: "3–4 portions", texture: "Smooth purée", tags: ["Freezer-friendly", "Veggie", "Batch cook"], ingredients: ["1 medium sweet potato, peeled & cubed", "Water or unsalted stock"], steps: ["Steam the sweet potato cubes for 12–15 min until very soft.", "Blend with a splash of the cooking water until silky.", "Cool to lukewarm and check the temperature before serving.", "Freeze extras in an ice-cube tray for quick meals."], tip: "Swap for butternut squash or carrot using the same method.", source: SRC.nhs },
  { id: "banana-mash", title: "Banana & Oat Mash", emoji: "🍌", minMonths: 6, maxMonths: 11, prepMins: 8, servings: "1 portion", texture: "Soft mash", tags: ["Breakfast", "No added sugar", "Quick"], ingredients: ["½ ripe banana", "1 tbsp baby porridge oats", "3 tbsp milk"], steps: ["Simmer the oats with milk for 3–4 min until soft and creamy.", "Mash the banana well and stir through.", "Loosen with a little extra milk if needed.", "Cool to warm before serving."], source: SRC.nhs },
  { id: "broccoli-trees", title: 'Steamed Broccoli "Trees"', emoji: "🥦", minMonths: 6, maxMonths: 24, prepMins: 12, servings: "2 portions", texture: "Soft finger food", tags: ["Baby-led", "Veggie", "First finger food"], ingredients: ["Broccoli florets with a long stalk to grip"], steps: ['Trim florets so each has a stalk "handle" for little hands.', "Steam for 8–10 min until soft enough to squash easily.", "Cool until just warm.", "Offer one floret at a time on the tray."], tip: "The floret head holds purées and sauces well for dipping later.", source: SRC.solidstarts },
  { id: "apple-pear-puree", title: "Apple & Pear Purée", emoji: "🍎", minMonths: 6, maxMonths: 10, prepMins: 18, servings: "4 portions", texture: "Smooth purée", tags: ["Fruit", "Freezer-friendly", "Batch cook"], ingredients: ["1 apple, peeled & chopped", "1 ripe pear, peeled & chopped", "Splash of water"], steps: ["Gently simmer the apple with a splash of water for 6–8 min.", "Add the pear and cook 2–3 min more until both are soft.", "Blend until smooth.", "Cool and serve, or freeze in cubes."], source: SRC.nhs },

  // ---------- 6 months+ · 🇸🇬 Singapore ----------
  { id: "sg-rice-cereal-veg", title: "Iron Rice Cereal with Veg Purée", emoji: "🍚", minMonths: 6, maxMonths: 10, prepMins: 10, servings: "1 portion", texture: "Smooth, slightly thicker than milk", tags: ["Singapore", "First food", "Iron-rich"], ingredients: ["2 tbsp iron-fortified baby rice cereal", "Breast milk or formula to mix", "1 tbsp pumpkin or carrot, steamed & puréed"], steps: ["Mix the rice cereal with warm milk to a smooth, runny paste.", "Stir in the steamed pumpkin or carrot purée for vitamins.", "Aim for a texture just thicker than milk so baby can lick it off the spoon.", "Introduce one new vegetable every 3–4 days."], tip: "HPB suggests iron-fortified cereal as a typical first food, with veg added for vitamin C to help iron absorption.", source: SRC.hhFirstFood },
  { id: "sg-papaya-banana", title: "Papaya & Banana Scrape", emoji: "🥭", minMonths: 6, maxMonths: 11, prepMins: 5, servings: "1 portion", texture: "Smooth mash", tags: ["Singapore", "No-cook", "Fruit"], ingredients: ["A wedge of ripe papaya", "½ ripe banana"], steps: ["Scrape the soft papaya flesh with a spoon into a bowl.", "Mash the banana and combine.", "Mix to a smooth, lump-free purée.", "Serve fresh — no added sugar needed."], tip: "SingHealth lists banana and papaya among soft, ripe local fruit ideal for scraping or mashing.", source: SRC.hxWean },
  { id: "sg-sweetpotato-congee", title: "Sweet Potato Brown-Rice Congee", emoji: "🥣", minMonths: 6, maxMonths: 18, prepMins: 35, servings: "3 portions", texture: "Soft, smooth congee", tags: ["Singapore", "Batch cook", "Veggie"], ingredients: ["3 tbsp white or brown rice, rinsed", "1 small sweet potato, diced", "2 cups water or unsalted stock"], steps: ["Simmer the rice with water until it breaks down into soft congee (~25–30 min).", "Add the sweet potato partway and cook until very soft.", "Blend or mash to the texture your baby is ready for.", "Cool to warm; freeze extra portions."], tip: "A classic local first congee — SingHealth suggests blended home-cooked rice porridge with mashed vegetables.", source: SRC.hxWean },

  // ---------- 8 months+ ----------
  { id: "lentil-veg-mash", title: "Red Lentil & Veg Mash", emoji: "🍲", minMonths: 8, maxMonths: 24, prepMins: 25, servings: "3 portions", texture: "Soft mash with lumps", tags: ["Iron-rich", "Protein", "Freezer-friendly"], ingredients: ["3 tbsp red lentils, rinsed", "1 small carrot, diced", "¼ onion, finely chopped", "1 tsp olive oil", "200ml unsalted stock or water"], steps: ["Soften the onion and carrot in the oil for 3–4 min.", "Add the lentils and stock, then simmer 18–20 min until very soft.", "Mash to a soft, lumpy texture (or blend for younger babies).", "Cool to warm before serving."], tip: "Iron from lentils absorbs better served with veg like this.", source: SRC.karmel },
  { id: "salmon-sweetpotato", title: "Salmon & Sweet Potato Mash", emoji: "🐟", minMonths: 8, maxMonths: 24, prepMins: 22, servings: "2 portions", texture: "Soft mash", tags: ["Omega-3", "Protein", "Allergen: fish"], ingredients: ["1 small skinless salmon fillet", "1 small sweet potato, cubed", "1 tbsp full-fat cream cheese or milk"], steps: ["Steam the sweet potato 12–15 min until soft.", "Add the salmon for the last 8 min until cooked through and flaking.", "Flake the salmon carefully, checking for any bones.", "Mash everything with the cream cheese until smooth and soft."], tip: "Introduce fish on its own first to watch for any reaction.", source: SRC.karmel },
  { id: "cheesy-scrambled-egg", title: "Soft Cheesy Scrambled Egg", emoji: "🍳", minMonths: 8, maxMonths: 99, prepMins: 8, servings: "1 portion", texture: "Soft curds", tags: ["Protein", "Breakfast", "Allergen: egg"], ingredients: ["1 egg", "1 tbsp milk", "1 tbsp grated mild cheese", "Knob of unsalted butter"], steps: ["Whisk the egg with the milk.", "Melt the butter in a pan on low heat.", "Add the egg and stir gently into soft curds — do not let it brown.", "Stir in the cheese off the heat and cool before serving."], tip: "Cook eggs until fully set for babies.", source: SRC.hlf },
  { id: "banana-oat-pancakes", title: "2-Ingredient Banana Pancakes", emoji: "🥞", minMonths: 8, maxMonths: 99, prepMins: 12, servings: "6 mini pancakes", texture: "Soft finger food", tags: ["Baby-led", "No added sugar", "Allergen: egg"], ingredients: ["1 ripe banana", "1 egg", "A little butter or oil for the pan"], steps: ["Mash the banana smooth, then whisk in the egg.", "Heat a lightly greased non-stick pan on low.", "Spoon small rounds and cook 1–2 min each side until set.", "Cool and cut into strips for little hands."], source: SRC.hlf },
  { id: "veggie-fritters", title: "Soft Courgette & Cheese Fritters", emoji: "🧆", minMonths: 8, maxMonths: 99, prepMins: 18, servings: "8 fritters", texture: "Soft finger food", tags: ["Baby-led", "Veggie", "Freezer-friendly"], ingredients: ["1 small courgette, grated & squeezed dry", "3 tbsp grated cheese", "1 egg", "3 tbsp flour"], steps: ["Mix the courgette, cheese, egg and flour into a thick batter.", "Heat a little oil in a non-stick pan on medium-low.", "Cook small spoonfuls 2 min each side until golden and set.", "Drain, cool and serve in baby-fist-sized strips."], source: SRC.bbc },

  // ---------- 8 months+ · 🇸🇬 Singapore ----------
  { id: "sg-fish-spinach-porridge", title: "Fish & Spinach Porridge", emoji: "🐠", minMonths: 8, maxMonths: 24, prepMins: 35, servings: "2 portions", texture: "Soft porridge, finely flaked", tags: ["Singapore", "Protein", "Allergen: fish"], ingredients: ["3 tbsp rice, rinsed", "2 cups water or unsalted stock", "A small piece of soft white fish (e.g. cod / threadfin)", "A few spinach leaves, finely chopped"], steps: ["Simmer the rice into a soft porridge (~25–30 min).", "Add the fish and cook until it flakes easily; check carefully for bones.", "Stir in the chopped spinach for the last 2 min.", "Mash to a soft, lump-suitable texture; cool to warm. No added salt."], tip: "SingHealth recommends finely flaked fish as a soft protein from around 7–8 months.", source: SRC.singhealth612 },
  { id: "sg-tofu-pumpkin", title: "Silken Tofu with Steamed Pumpkin", emoji: "🧈", minMonths: 8, maxMonths: 24, prepMins: 15, servings: "2 portions", texture: "Soft mash", tags: ["Singapore", "Plant protein", "Allergen: soy"], ingredients: ["½ block soft silken tofu", "A wedge of pumpkin, cubed"], steps: ["Steam the pumpkin 10–12 min until very soft.", "Warm the silken tofu briefly (steam or blanch).", "Mash the pumpkin and tofu together until smooth and soft.", "Serve warm — a gentle, iron- and protein-friendly local staple."], tip: "HPB lists soybean curd (tofu) among soft, protein-rich first foods.", source: SRC.hhSolids },

  // ---------- 10 months+ ----------
  { id: "mini-meatballs", title: "Soft Chicken Mini Meatballs", emoji: "🍖", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "12 small meatballs", texture: "Soft chopped", tags: ["Protein", "Iron-rich", "Freezer-friendly"], ingredients: ["150g chicken or turkey mince", "2 tbsp soft breadcrumbs", "1 tbsp grated apple or courgette", "1 tsp dried herbs"], steps: ["Mix everything and roll into small, soft meatballs.", "Brown gently in a little oil, then add a splash of water.", "Cover and steam-cook 8–10 min until cooked through.", "Cool, then quarter for younger eaters."], tip: "Simmer in a no-salt tomato sauce to serve with pasta.", source: SRC.karmel },
  { id: "pasta-tomato", title: "Hidden-Veg Tomato Pasta", emoji: "🍝", minMonths: 10, maxMonths: 99, prepMins: 22, servings: "3 portions", texture: "Soft chopped", tags: ["Veggie", "Batch cook", "Family meal"], ingredients: ["Small pasta shapes (e.g. macaroni)", "1 carrot + ½ courgette, grated", "1 tin chopped tomatoes (no salt)", "1 tsp olive oil", "Grated cheese to finish"], steps: ["Soften the grated veg in the oil for 5 min.", "Add the tomatoes and simmer 12 min until thick.", "Blend smooth if you like, then toss with cooked pasta.", "Stir in cheese and cool to warm before serving."], source: SRC.bbc },
  { id: "fish-cakes", title: "Mini Salmon Fish Cakes", emoji: "🐠", minMonths: 10, maxMonths: 99, prepMins: 28, servings: "8 small cakes", texture: "Soft finger food", tags: ["Omega-3", "Baby-led", "Allergen: fish"], ingredients: ["1 cooked salmon fillet, flaked", "1 small potato, boiled & mashed", "2 tbsp sweetcorn or peas", "1 tbsp flour for shaping"], steps: ["Mix the salmon, mash and veg; check for bones.", "Shape into small patties and dust lightly with flour.", "Pan-fry in a little oil 2–3 min each side until golden.", "Cool and cut into strips."], source: SRC.karmel },
  { id: "porridge-fingers", title: "Baked Oat Porridge Fingers", emoji: "🌾", minMonths: 10, maxMonths: 99, prepMins: 30, servings: "10 fingers", texture: "Soft finger food", tags: ["Breakfast", "No added sugar", "Freezer-friendly"], ingredients: ["1 cup oats", "1 mashed banana", "1 cup milk", "1 egg", "Handful blueberries"], steps: ["Mix everything into a loose batter and pour into a lined tin.", "Bake at 180°C for 20–25 min until set and golden.", "Cool fully, then slice into grabbable fingers.", "Great warm or cold; freezes well."], source: SRC.hlf },
  { id: "sg-chicken-carrot-congee", title: "Minced Chicken & Carrot Congee", emoji: "🍜", minMonths: 10, maxMonths: 99, prepMins: 35, servings: "3 portions", texture: "Soft congee with fine lumps", tags: ["Singapore", "Protein", "Family meal"], ingredients: ["4 tbsp rice, rinsed", "2½ cups water or unsalted stock", "2 tbsp minced chicken", "1 small carrot, finely diced"], steps: ["Simmer the rice and carrot into a soft congee (~25 min).", "Stir in the minced chicken and cook until fully done.", "Mash any lumps to a texture your baby can manage.", "Cool to warm; season for adults separately, not for baby."], tip: "An everyday local porridge — SingHealth suggests minced meat added to rice porridge as texture develops.", source: SRC.singhealth612 },

  // ---------- 12 months+ ----------
  { id: "veg-omelette", title: "Cheese & Veg Omelette Bites", emoji: "🧀", minMonths: 12, maxMonths: 99, prepMins: 15, servings: "6 bites", texture: "Soft finger food", tags: ["Protein", "Veggie", "Allergen: egg"], ingredients: ["2 eggs", "2 tbsp grated cheese", "3 tbsp finely chopped cooked veg", "Knob of butter"], steps: ["Whisk the eggs with the cheese and veg.", "Pour into a greased muffin tin or small pan.", "Bake at 180°C for 12–14 min (or pan-cook) until set.", "Cool and cut into toddler-sized squares."], source: SRC.hlf },
  { id: "chicken-veg-curry", title: "Mild Chicken & Coconut Curry", emoji: "🍛", minMonths: 12, maxMonths: 99, prepMins: 30, servings: "3 portions", texture: "Soft chopped", tags: ["Protein", "Family meal", "Batch cook"], ingredients: ["1 chicken breast, diced small", "½ onion + 1 carrot, finely chopped", "½ tsp mild curry powder", "150ml coconut milk", "Cooked rice to serve"], steps: ["Soften the onion and carrot, then stir in the curry powder.", "Add the chicken and brown for 3–4 min.", "Pour in the coconut milk and simmer 12–15 min until tender.", "Chop any large pieces small and serve over soft rice."], tip: "Keep it salt-free; let adults season their own bowls.", source: SRC.karmel },
  { id: "pita-pizza", title: "Mini Pita Pizzas", emoji: "🍕", minMonths: 12, maxMonths: 99, prepMins: 15, servings: "2 pizzas", texture: "Soft finger food", tags: ["Quick", "Veggie", "Family meal"], ingredients: ["1 wholemeal pita or muffin", "2 tbsp no-salt tomato sauce", "Grated mozzarella", "Finely chopped soft veg toppings"], steps: ["Spread the tomato sauce over the pita base.", "Scatter cheese and soft veg on top.", "Bake at 190°C for 8–10 min until the cheese melts.", "Cool and cut into small wedges or strips."], source: SRC.bbc },
  { id: "sg-steamed-egg", title: "Silky Steamed Egg with Fish", emoji: "🥚", minMonths: 12, maxMonths: 99, prepMins: 18, servings: "2 portions", texture: "Silky soft custard", tags: ["Singapore", "Protein", "Allergen: egg, fish"], ingredients: ["1 egg", "80ml unsalted stock or water", "1 tbsp finely flaked cooked fish", "A few peas or chopped soft veg"], steps: ["Whisk the egg with the stock and strain for a smooth custard.", "Stir in the flaked fish and soft veg in a heatproof bowl.", "Steam on low 10–12 min until just set and silky.", "Cool to warm; serve with soft rice."], tip: "HealthXchange lists egg and fish among top foods for growing children — steam until fully set.", source: SRC.hxGrowing },

  // ---------- 18 months+ ----------
  { id: "veggie-muffins", title: "Savoury Veggie Muffins", emoji: "🧁", minMonths: 18, maxMonths: 99, prepMins: 30, servings: "12 mini muffins", texture: "Soft handheld", tags: ["Lunchbox", "Veggie", "Freezer-friendly"], ingredients: ["1½ cups self-raising flour", "1 grated carrot + handful sweetcorn", "½ cup grated cheese", "1 egg + ¾ cup milk", "3 tbsp oil"], steps: ["Mix the wet ingredients, then fold in the dry ingredients and veg.", "Spoon into a mini-muffin tin.", "Bake at 180°C for 18–20 min until risen and golden.", "Cool fully; great in lunchboxes or as a snack."], source: SRC.hlf },
  { id: "pasta-salad", title: "Toddler Pasta Salad Cups", emoji: "🥗", minMonths: 18, maxMonths: 99, prepMins: 18, servings: "3 portions", texture: "Soft chopped", tags: ["Lunchbox", "No-cook assembly", "Veggie"], ingredients: ["Cooked small pasta", "Soft cherry tomatoes, quartered", "Cucumber, diced small", "Cubes of mild cheese", "1 tsp olive oil"], steps: ["Cool the cooked pasta under cold water and drain.", "Quarter the tomatoes and finely dice the other veg.", "Toss everything with a little olive oil.", "Serve cool — perfect for picnics and lunchboxes."], tip: "Always quarter grapes and tomatoes to reduce choking risk.", source: SRC.bbc },
  { id: "sweet-potato-chili", title: "Mild Beef & Sweet Potato Chilli", emoji: "🫘", minMonths: 18, maxMonths: 99, prepMins: 35, servings: "4 portions", texture: "Soft chopped", tags: ["Iron-rich", "Family meal", "Batch cook"], ingredients: ["250g lean beef mince", "1 sweet potato, diced small", "½ tin kidney beans, rinsed & mashed", "1 tin chopped tomatoes (no salt)", "½ tsp mild paprika"], steps: ["Brown the mince, then add the sweet potato and paprika.", "Stir in the tomatoes and beans.", "Simmer 20–25 min until the sweet potato is tender.", "Mash any firm pieces and serve with rice or soft tortilla."], tip: "Mash the beans so they are not a choking hazard.", source: SRC.karmel },

  // ---------- @carynechua (TikTok) ----------
  { id: "baby-chawanmushi-veggie-egg-custard", title: "Baby Chawanmushi (Veggie Egg Custard)", emoji: "🍮", minMonths: 8, maxMonths: 99, prepMins: 10, servings: "1–2 baby portions", texture: "Silky custard", tags: ["Iron-rich", "Protein", "Egg", "Veggie"], ingredients: ["1 egg", "50ml warm water", "Cooked broccoli, finely chopped", "Cooked carrot, finely chopped"], steps: ["Crack 1 egg into a bowl.", "Add 50ml warm water.", "Beat quickly until smooth.", "Strain through a sieve into a heatproof container.", "Stir in finely chopped cooked broccoli and carrot.", "Spoon off any bubbles on top.", "Cover with cling film.", "Steam over medium heat about 10 minutes until just set."], tip: "Smooth and no teeth needed — packed with iron, protein and veggie goodness.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7513932591762820370" } },
  { id: "babys-first-rice-cereal", title: "Baby's First Rice Cereal", emoji: "🥣", minMonths: 6, maxMonths: 99, prepMins: 2, servings: "1 baby portion", texture: "Smooth purée", tags: ["Iron-rich", "Breakfast"], ingredients: ["Single-grain baby rice cereal", "Breast milk or formula"], steps: ["Spoon some single-grain rice cereal into a bowl.", "Add a little breast milk or formula.", "Stir to a smooth, runny purée, thickening it over the following days.", "Offer small spoonfuls and let baby explore the spoon."], tip: "Start thin and follow baby's interest rather than aiming for a full meal on day one.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7484493936023620882" } },
  { id: "avocado-two-ways-sticks-and-pur-e", title: "Avocado Two Ways: Sticks & Purée", emoji: "🥑", minMonths: 6, maxMonths: 99, prepMins: 10, servings: "1–2 baby portions", texture: "Smooth purée", tags: ["Fruit", "Finger-food", "No-cook"], ingredients: ["1 ripe avocado"], steps: ["Choose a fully ripe avocado, halve it and remove the pit.", "For sticks, cut into 3–4cm pieces that are easy for little hands to grip.", "For purée, scoop out the flesh and mash or blend until smooth and creamy.", "Serve sticks for self-feeding or the purée on a spoon."], tip: "Same avocado, two ways — sticks for baby-led weaning or a smooth purée for spoon-feeding.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7494267971292892434" } },
  { id: "3-ingredient-pumpkin-sticks", title: "3-Ingredient Pumpkin Sticks", emoji: "🎃", minMonths: 10, maxMonths: 99, prepMins: 30, servings: "2–3 baby portions", texture: "Soft finger food", tags: ["Veggie", "Finger-food", "Freezer-friendly"], ingredients: ["50g pumpkin", "50g cake flour", "60g water", "A little oil, for the moulds"], steps: ["Chop the pumpkin and steam until soft, then blend smooth.", "Combine 50g pumpkin purée, 50g cake flour and 60g water.", "Blend again until the batter looks like yogurt.", "Brush silicone moulds with a little oil.", "Pipe the batter into the moulds about 80% full.", "Tap the moulds to release air bubbles.", "Steam for 20 minutes, then unmould and serve."], tip: "Soft and chewy, perfect for little hands — egg-free and dairy-free.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7507624890913279239" } },
  { id: "baby-pumpkin-pancakes", title: "Baby Pumpkin Pancakes", emoji: "🥞", minMonths: 7, maxMonths: 99, prepMins: 30, servings: "About 8 mini pancakes", texture: "Pancake / fritter", tags: ["Veggie", "Egg", "Breakfast", "Finger-food"], ingredients: ["30g pumpkin purée", "40g breast milk or formula", "30g cake flour", "1 egg yolk"], steps: ["Steam pumpkin cubes until soft, then blend into a smooth purée.", "Whisk 30g pumpkin purée, 40g milk, 30g cake flour and 1 egg yolk into a smooth, lump-free batter.", "Spoon the batter into a piping bag and snip the tip.", "Squeeze small coin shapes onto a dry pan over low heat.", "Flip when golden and bubbly, then serve."], tip: "Squeeze the batter into round coins that are easy for little hands to grip.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7510222178298662152" } },
  { id: "babys-first-egg-yolk", title: "Baby's First Egg Yolk", emoji: "🥚", minMonths: 6, maxMonths: 99, prepMins: 15, servings: "1 baby portion", texture: "Mashed", tags: ["Egg", "Protein", "Iron-rich"], ingredients: ["1 egg (yolk only)", "Breast milk or water, to loosen"], steps: ["Hard-boil the egg until fully cooked.", "Peel and remove all the white, keeping only the yolk.", "Mash the yolk into small pieces.", "Loosen to a soft texture with a little breast milk or water.", "Offer a small amount first and watch for any reaction."], tip: "Egg is a common allergen — introduce just the yolk in a tiny amount and monitor.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7510598033818750226" } },
  { id: "banana-with-peanut-butter", title: "Banana with Peanut Butter", emoji: "🍌", minMonths: 6, maxMonths: 99, prepMins: 5, servings: "1 baby portion", texture: "Soft finger food", tags: ["Fruit", "Protein", "No-cook", "Finger-food"], ingredients: ["1 banana", "Smooth peanut butter (unsweetened, unsalted)"], steps: ["Spoon a little smooth peanut butter into a bowl.", "Peel a banana and dip it into the peanut butter.", "Let baby self-feed the coated banana."], tip: "Peanut is a common allergen — best introduced from 6 months with smooth, unsweetened peanut butter.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7511706162304257287" } },
  { id: "chicken-tomato-and-spinach-porridge", title: "Chicken, Tomato & Spinach Porridge", emoji: "🥣", minMonths: 7, maxMonths: 99, prepMins: 40, servings: "2–3 baby portions", texture: "Porridge / congee", tags: ["Protein", "Iron-rich", "Chicken", "Veggie"], ingredients: ["Rice", "Tomato", "Minced chicken", "Spinach", "Chicken & vegetable broth (no salt)"], steps: ["Soak the rice 20–30 minutes so it cooks soft.", "Finely chop the tomato and spinach.", "Add rice, minced chicken, tomato, spinach and broth to a porridge cooker.", "Cook until creamy and soft.", "Stir and serve once cooled to a safe temperature."], tip: "No salt or seasoning needed — the soft texture helps baby learn to swallow.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7513562622248209682" } },
  { id: "prawn-and-veggie-balls", title: "Prawn & Veggie Balls", emoji: "🍤", minMonths: 10, maxMonths: 99, prepMins: 20, servings: "3–4 baby portions", texture: "Soft bite-sized", tags: ["Protein", "Veggie", "Finger-food"], ingredients: ["100g prawns", "30g yam", "Carrot, finely chopped", "Broccoli, finely chopped", "1 tbsp cake flour"], steps: ["Blend prawns with yam into a lightly textured paste.", "Mix in chopped carrot, broccoli and cake flour.", "Pipe small balls into boiling water.", "Simmer until the balls float, then scoop out and drain.", "Serve once cooled."], tip: "Soft, chewy and perfect for tiny hands and gums.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7515047163089440007" } },
  { id: "spinach-egg-pancake-rolls", title: "Spinach Egg Pancake Rolls", emoji: "🥬", minMonths: 8, maxMonths: 99, prepMins: 15, servings: "2–3 baby portions", texture: "Pancake / fritter", tags: ["Egg", "Veggie", "Iron-rich"], ingredients: ["A bowlful of spinach", "1 egg", "1 tsp black sesame seeds", "1 tsp grated cheese"], steps: ["Blend spinach with a little water, then strain out the green juice.", "Whisk the spinach juice with egg, black sesame and grated cheese into a smooth batter.", "Pour into a pan and cook into a thin sheet, then flip.", "Roll up the pancake and slice into bite-sized rolls."], tip: "Roll and slice so it's easy for little hands to grip.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7515788165647568146" } },
  { id: "pear-yam-and-red-date-porridge", title: "Pear, Yam & Red Date Porridge", emoji: "🍐", minMonths: 8, maxMonths: 99, prepMins: 40, servings: "3–4 baby portions", texture: "Porridge / congee", tags: ["Fruit", "Veggie", "Breakfast"], ingredients: ["1 pear", "Chinese yam", "Red dates", "Rice", "About 200ml water"], steps: ["Peel and dice the pear into small chunks.", "Peel and chop the Chinese yam.", "Pit the red dates and chop small.", "Add rice, pear, yam and red dates to a pot with water.", "Cook together until soft and porridgey."], tip: "A naturally sweet, gentle porridge that's easy to digest.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7516157290035170568" } },
  { id: "banana-egg-bites", title: "Banana Egg Bites", emoji: "🍌", minMonths: 8, maxMonths: 99, prepMins: 15, servings: "2–3 baby portions", texture: "Soft bite-sized", tags: ["Egg", "Fruit", "Breakfast"], ingredients: ["1 banana", "1 egg yolk", "1 tbsp cake flour", "Black sesame seeds"], steps: ["Slice the banana into thick rounds.", "Whisk the egg yolk with cake flour into a smooth batter.", "Dip each banana slice into the batter to coat.", "Pan-fry, sprinkle with sesame and flip until golden on both sides."], tip: "Sprinkle sesame seeds on top before flipping for extra flavour.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7516901745591684360" } },
  { id: "veggie-baby-dumplings", title: "Veggie Baby Dumplings", emoji: "🥟", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "4–5 baby portions", texture: "Soft bite-sized", tags: ["Veggie", "Finger-food"], ingredients: ["Broccoli", "Carrot", "Sweetcorn", "Dumpling wrappers"], steps: ["Steam the broccoli, carrot and corn until soft.", "Blend the cooked vegetables into a chunky filling.", "Spoon a little filling onto each dumpling wrapper.", "Fold and seal the edges, pressing with a cutter.", "Steam the dumplings until cooked through."], tip: "Only a handful of ingredients and easy to seal with a press cutter.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7517271665814834439" } },
  { id: "purple-sweet-potato-and-egg-pudding", title: "Purple Sweet Potato & Egg Pudding", emoji: "🍠", minMonths: 8, maxMonths: 99, prepMins: 20, servings: "2 baby portions", texture: "Silky custard", tags: ["Egg", "Veggie"], ingredients: ["Purple sweet potato", "Chinese yam", "1 egg", "Milk or formula"], steps: ["Steam and mash the purple sweet potato, pressing through a sieve until smooth.", "Steam and mash the Chinese yam separately until smooth.", "Whisk the egg with milk and strain.", "Layer the purple potato, yam and egg mixture in a cup.", "Steam until set into a soft pudding."], tip: "Strain the egg mixture for an extra-silky custard.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7518013503484005640" } },
  { id: "broccoli-and-egg-yolk-flowers", title: "Broccoli & Egg Yolk Flowers", emoji: "🥦", minMonths: 8, maxMonths: 99, prepMins: 20, servings: "2–3 baby portions", texture: "Pancake / fritter", tags: ["Egg", "Veggie", "Iron-rich"], ingredients: ["Broccoli", "1 tbsp cake flour", "1 egg yolk"], steps: ["Steam and blend the broccoli into a smooth purée.", "Mix the purée with cake flour into a pipeable green batter.", "Whisk the egg yolk separately.", "Pipe broccoli batter into flower-petal shapes in the pan, then add egg-yolk centres.", "Cook gently until set."], tip: "Pipe the petals first, then add a yolk centre for the flower look.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7518756759146728711" } },
  { id: "veggie-rice-balls", title: "Veggie Rice Balls", emoji: "🍙", minMonths: 10, maxMonths: 99, prepMins: 20, servings: "4–5 baby portions", texture: "Soft bite-sized", tags: ["Veggie", "Finger-food"], ingredients: ["Cooked rice", "Carrot, chopped", "Broccoli, chopped", "1 egg yolk", "Cake flour"], steps: ["Combine cooked rice with chopped carrot, broccoli and cake flour.", "Mix in the egg yolk to make a sticky mixture.", "With clean (gloved) hands, roll into small balls.", "Pan-fry or cook the balls until golden and set."], tip: "Roll small balls for easy little-hand grips.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7519306417535323410" } },
  { id: "purple-sweet-potato-egg-tarts", title: "Purple Sweet Potato Egg Tarts", emoji: "🍠", minMonths: 8, maxMonths: 99, prepMins: 25, servings: "4–5 baby portions", texture: "Soft bite-sized", tags: ["Egg", "Veggie"], ingredients: ["Purple sweet potato", "2 egg yolks", "Milk or formula", "1 tbsp cake flour"], steps: ["Steam and mash the purple sweet potato until smooth.", "Mix the mash with cake flour and knead into a dough.", "Whisk the egg yolks with milk for the custard filling.", "Shape the purple dough into small tart cases.", "Fill with the custard and steam or bake until set."], tip: "Soft, creamy and perfect for little ones.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7519500311434759431" } },
  { id: "eggless-mango-chawanmushi", title: "Eggless Mango Chawanmushi", emoji: "🥭", minMonths: 8, maxMonths: 99, prepMins: 15, servings: "2 baby portions", texture: "Silky custard", tags: ["Fruit", "No-cook", "Tofu"], ingredients: ["Mango", "Silken tofu", "Milk or formula"], steps: ["Add chopped mango and silken tofu to a blender.", "Blend with a little milk until completely smooth.", "Pour into a cup or container.", "Chill or lightly steam until set into a soft pudding."], tip: "Eggless and safe for babies allergic to egg.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7519870147369209095" } },
  { id: "cheesy-potato-pancakes", title: "Cheesy Potato Pancakes", emoji: "🥔", minMonths: 10, maxMonths: 99, prepMins: 15, servings: "3–4 baby portions", texture: "Pancake / fritter", tags: ["Veggie", "Dairy", "Finger-food"], ingredients: ["Potato", "Carrot", "Grated cheese", "Cake flour"], steps: ["Steam the potato until soft, then mash finely.", "Mix with grated carrot, cheese and cake flour.", "Shape into small flat patties.", "Pan-fry until golden on both sides."], tip: "Rich in calcium and done in under 10 minutes.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7520241250977549586" } },
  { id: "fluffy-blueberry-cakes", title: "Fluffy Blueberry Cakes", emoji: "🫐", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "6 mini cakes", texture: "Soft bite-sized", tags: ["Fruit", "Egg", "Breakfast"], ingredients: ["Chinese yam", "Blueberries", "1 egg", "Cake flour"], steps: ["Steam and blend the Chinese yam with egg until smooth.", "Mix in cake flour to a fluffy batter.", "Spoon into a silicone mould.", "Press blueberries into each cake.", "Steam until risen and set."], tip: "Rich in fibre and naturally sweet from the blueberries.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7521358087576456466" } },
  { id: "baby-dorayaki", title: "Baby Dorayaki", emoji: "🥞", minMonths: 10, maxMonths: 99, prepMins: 20, servings: "4–5 mini pancakes", texture: "Pancake / fritter", tags: ["Fruit", "Egg", "Breakfast"], ingredients: ["Apple", "Purple sweet potato", "1 egg", "Cake flour"], steps: ["Steam the apple and purple sweet potato until soft.", "Blend the apple with egg and cake flour into a smooth batter.", "Cook small round pancakes until golden.", "Mash the steamed purple sweet potato into a filling.", "Sandwich the filling between two pancakes."], tip: "Sandwich with purple sweet potato for a fun, fibre-rich filling.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7522840085880933650" } },
  { id: "creamy-pumpkin-baby-noodles", title: "Creamy Pumpkin Baby Noodles", emoji: "🎃", minMonths: 10, maxMonths: 99, prepMins: 20, servings: "2–3 baby portions", texture: "Soft bite-sized", tags: ["Veggie", "One-pan"], ingredients: ["Pumpkin", "Baby noodles (somen)", "Carrot", "Broccoli"], steps: ["Steam and mash the pumpkin until smooth and creamy.", "Break the baby noodles into short lengths.", "Simmer the noodles with finely chopped carrot until soft.", "Stir the pumpkin mash through the noodles until creamy.", "Add chopped broccoli and cook briefly to finish."], tip: "The pumpkin makes a naturally creamy sauce, no dairy needed.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7523952571980057874" } },
  { id: "baby-banana-cakes", title: "Baby Banana Cakes", emoji: "🍌", minMonths: 8, maxMonths: 99, prepMins: 15, servings: "6–8 mini cakes", texture: "Soft bite-sized", tags: ["Fruit", "Egg", "Breakfast", "Finger-food"], ingredients: ["Banana", "Cake flour", "1 egg", "A little cocoa (optional, for colour)"], steps: ["Blend banana and egg into a smooth batter.", "Stir in cake flour; fold cocoa into one half for two colours.", "Spoon the mixtures into a piping bag.", "Pipe into a greased shaped silicone mould.", "Steam until set, then cool and turn out."], tip: "High in fibre and iron; no sugar, no yeast and ready in under 30 minutes.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7525063188342197511" } },
  { id: "beef-finger-sticks", title: "Beef Finger Sticks", emoji: "🥩", minMonths: 8, maxMonths: 99, prepMins: 20, servings: "6–8 sticks", texture: "Soft finger food", tags: ["Iron-rich", "Protein", "Finger-food"], ingredients: ["Beef", "Carrot", "Broccoli", "A little starch"], steps: ["Blend the beef into a smooth paste.", "Add chopped carrot, broccoli and a little starch, then pulse to combine.", "Pipe the mixture into long finger-stick shapes.", "Pan-fry or steam until cooked through.", "Cool slightly and serve as soft self-feeding sticks."], tip: "Iron-rich finger food for babies starting to self-feed.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7525808741376199944" } },
  { id: "easy-salmon-rice-balls", title: "Easy Salmon Rice Balls", emoji: "🍙", minMonths: 10, maxMonths: 99, prepMins: 15, servings: "5–6 rice balls", texture: "Soft bite-sized", tags: ["Fish", "Finger-food", "Protein"], ingredients: ["Cooked rice", "Salmon fillet", "Carrot, finely diced", "Seaweed (nori)", "Sesame seeds"], steps: ["Blanch the diced carrot until soft.", "Pan-fry the salmon, then flake and remove any bones.", "Mix rice with flaked salmon, carrot, chopped seaweed and sesame.", "Press into a rice-ball mould.", "Shake to form neat balls and serve."], tip: "Great for little hands learning to self-feed.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7526548394093841682" } },
  { id: "homemade-chicken-and-veggie-sausage", title: "Homemade Chicken & Veggie Sausage", emoji: "🌭", minMonths: 8, maxMonths: 99, prepMins: 25, servings: "6–8 sausages", texture: "Soft finger food", tags: ["Chicken", "Protein", "Veggie", "Finger-food"], ingredients: ["Chicken breast", "Broccoli", "Carrot", "Corn", "A little starch", "A little oil"], steps: ["Blanch broccoli, carrot and corn until soft, then chop finely.", "Blend the chicken with a little oil into a smooth paste.", "Mix the chicken paste with the chopped vegetables and starch.", "Pipe into a sausage-shaped silicone mould.", "Steam until firm and cooked through, then cool and unmould."], tip: "No added salt or sugar — a wholesome homemade sausage for babies.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7527293570231946503" } },
  { id: "sweet-potato-balls", title: "Sweet Potato Balls", emoji: "🍠", minMonths: 8, maxMonths: 99, prepMins: 15, servings: "6–8 balls", texture: "Mashed", tags: ["Veggie", "Finger-food", "Snack"], ingredients: ["Sweet potato"], steps: ["Peel and slice the sweet potato, then steam until very soft.", "Mash until smooth.", "Scoop portions into a piping bag.", "Twist and roll to shape neat round balls.", "Turn out and serve as soft hand-held balls."], tip: "Just one main ingredient — naturally sweet, soft balls perfect for babies.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7528407269437099271" } },
  { id: "apple-butter-chicken-drumstick", title: "Apple Butter Chicken Drumstick", emoji: "🍗", minMonths: 10, maxMonths: 99, prepMins: 40, servings: "2 drumsticks", texture: "Soft bite-sized", tags: ["Chicken", "Protein", "Fruit", "Iron-rich"], ingredients: ["Chicken drumsticks", "Apple, sliced", "Onion", "Butter"], steps: ["Melt butter in a pan and soften the sliced onion.", "Add apple slices and cook until fragrant and golden.", "Brown the chicken drumsticks.", "Transfer everything to a slow cooker with a little water.", "Slow-cook until the chicken is tender and falls off the bone."], tip: "Apple and onion make a naturally sweet sauce — shred the meat off the bone before serving.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7530259680904350984" } },
  { id: "homemade-baby-chicken-broth-cubes", title: "Homemade Baby Chicken Broth Cubes", emoji: "🍲", minMonths: 6, maxMonths: 99, prepMins: 60, servings: "1 tray of freezer cubes", texture: "Smooth purée", tags: ["Chicken", "Freezer-friendly", "Veggie"], ingredients: ["Chicken drumsticks", "Corn", "Carrot", "Potato"], steps: ["Blanch the chicken drumsticks to clean them.", "Add chicken, corn, carrot and potato to a slow cooker with water.", "Slow-cook for several hours into a rich broth.", "Strain and pour into ice-cube trays.", "Freeze, then pop out cubes to flavour baby meals."], tip: "Batch broth — freeze in cubes and add to congee or purées anytime.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7531745779573165319" } },
  { id: "baby-pumpkin-layered-cakes", title: "Baby Pumpkin Layered Cakes", emoji: "🎃", minMonths: 8, maxMonths: 99, prepMins: 30, servings: "4–6 slices", texture: "Silky custard", tags: ["Veggie", "Egg", "Dairy"], ingredients: ["Pumpkin, sliced", "2 egg yolks", "Milk"], steps: ["Steam the pumpkin slices until very soft.", "Whisk egg yolks with milk into a smooth custard.", "Layer pumpkin slices in a bowl.", "Strain the custard over the pumpkin layers.", "Steam until just set, then slice."], tip: "Strain the custard for an extra-smooth, silky texture.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7533598847335992594" } },
  { id: "baby-beef-bolognese-pasta", title: "Baby Beef Bolognese Pasta", emoji: "🍝", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "2–3 baby portions", texture: "Soft bite-sized", tags: ["Iron-rich", "Protein", "Veggie", "One-pan"], ingredients: ["Fusilli pasta", "Beef mince", "Tomato", "Carrot", "Onion", "Garlic"], steps: ["Blend tomato, carrot and onion into a smooth sauce.", "Cook the pasta until very soft, then drain.", "Sauté garlic, then brown the beef mince.", "Add the blended sauce and simmer until thick.", "Stir the cooked pasta through the bolognese."], tip: "Iron-rich beef bolognese with hidden veg — cook the pasta extra-soft.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7534342632856734984" } },
  { id: "rice-cooker-chicken-rice-balls", title: "Rice Cooker Chicken Rice Balls", emoji: "🍚", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "5–6 rice balls", texture: "Soft bite-sized", tags: ["Chicken", "Protein", "Finger-food"], ingredients: ["Cooked rice", "Chicken breast", "King oyster mushroom", "Onion", "Ginger"], steps: ["Finely chop the mushroom and onion.", "Sauté onion, ginger and mushroom until fragrant.", "Cook the chicken, then shred or chop small.", "Mix the chicken and vegetables through cooked rice.", "Shape into balls and finish in the rice cooker."], tip: "An easy one-pot chicken rice for little hands.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7535825663320689928" } },
  { id: "cod-and-prawn-tofu-cubes", title: "Cod & Prawn Tofu Cubes", emoji: "🐟", minMonths: 8, maxMonths: 99, prepMins: 30, servings: "1 tray of cubes", texture: "Silky custard", tags: ["Fish", "Protein", "Veggie", "Freezer-friendly"], ingredients: ["Cod fillet", "Prawns", "Corn", "Carrot", "1 egg", "A little starch", "A little oil"], steps: ["Blend cod, prawns, oil, egg and starch into a smooth paste.", "Stir in finely chopped corn and carrot.", "Pour into a lined dish and smooth the top.", "Steam until firmly set like a soft tofu block.", "Cool, then cut into bite-sized cubes."], tip: "A soft tofu-textured fish block — freeze the cubes for easy protein meals.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7536941353507294472" } },
  { id: "soft-potato-balls-in-carrot-soup", title: "Soft Potato Balls in Carrot Soup", emoji: "🥔", minMonths: 10, maxMonths: 99, prepMins: 30, servings: "2–3 baby portions", texture: "Soft bite-sized", tags: ["Veggie", "Egg", "Finger-food"], ingredients: ["Potato", "Carrot", "1 egg yolk", "A little starch"], steps: ["Steam the potato until soft, then mash smooth.", "Mix with a little starch and knead into a dough.", "Roll into small bite-sized balls.", "Grate carrot and simmer into a light soup.", "Add the potato balls, cook through, then stir in beaten egg yolk."], tip: "Soft potato balls in a gentle carrot soup — easy to chew and full of veg.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7538053143003712776" } },
  { id: "tomato-beef-rice", title: "Tomato Beef Rice", emoji: "🍅", minMonths: 8, maxMonths: 99, prepMins: 20, servings: "2–3 baby portions", texture: "Soft bite-sized", tags: ["Iron-rich", "Protein", "Veggie", "One-pan"], ingredients: ["Beef", "Tomato", "Carrot", "Cooked rice", "1 egg", "Spring onion"], steps: ["Finely chop the carrot, tomato and spring onion.", "Mince the beef into small pieces.", "Scramble the egg in a pan, then set aside.", "Brown the beef, add carrot and tomato and cook until soft.", "Stir in cooked rice and the scrambled egg.", "Finish with spring onion and combine."], tip: "No teeth, no problem — keep everything finely chopped and soft.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7540650182275386642" } },
  { id: "cold-chicken-shredded-noodles", title: "Cold Chicken Shredded Noodles", emoji: "🍜", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "1–2 baby portions", texture: "Soft finger food", tags: ["Protein", "Veggie", "Egg", "Chicken"], ingredients: ["Chicken breast", "Noodles", "Carrot", "Cucumber", "1 egg"], steps: ["Poach the chicken until cooked, then cool and shred.", "Cut carrot and cucumber into thin matchsticks.", "Make a thin omelette and slice into strips.", "Boil the noodles, cool and cut into short lengths.", "Arrange noodles, chicken, vegetables and egg together."], tip: "Serve cool and cut noodles short so little hands can pick them up.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7541392228489383176" } },
  { id: "purple-cabbage-prawn-bites", title: "Purple Cabbage Prawn Bites", emoji: "🦐", minMonths: 8, maxMonths: 99, prepMins: 25, servings: "2–3 baby portions", texture: "Soft finger food", tags: ["Protein", "Veggie", "Finger-food"], ingredients: ["Purple cabbage", "Prawns", "Spinach", "A little cornstarch"], steps: ["Blitz the purple cabbage finely.", "Blitz the prawns into a smooth paste.", "Finely chop the spinach.", "Mix cabbage, prawn paste, spinach and cornstarch.", "Pipe small rounds onto a non-stick mat.", "Pan-fry until cooked and lightly set."], tip: "No teeth, no problem — soft enough to mash with gums.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7542134859607624967" } },
  { id: "savoury-salmon-oatmeal", title: "Savoury Salmon Oatmeal", emoji: "🥣", minMonths: 8, maxMonths: 99, prepMins: 15, servings: "1–2 baby portions", texture: "Porridge / congee", tags: ["Fish", "Veggie", "Iron-rich", "Breakfast"], ingredients: ["Salmon", "Oats", "Broccoli", "Mushroom", "Milk"], steps: ["Finely chop the mushroom and broccoli.", "Cut the salmon into small pieces.", "Sauté the broccoli and mushroom until soft.", "Add salmon and break it up as it cooks through.", "Stir in oats and a splash of milk.", "Cook until creamy and porridge-like."], tip: "Cook the oats soft and creamy for an easy savoury breakfast.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7543251109578657031" } },
  { id: "7-veggie-japanese-baby-curry-rice", title: "7-Veggie Japanese Baby Curry Rice", emoji: "🍛", minMonths: 8, maxMonths: 99, prepMins: 30, servings: "Freezer batch", texture: "Smooth purée", tags: ["Veggie", "Freezer-friendly", "Fruit"], ingredients: ["Potato", "Carrot", "Pumpkin", "Apple", "Onion", "Tomato", "A little butter"], steps: ["Peel and chop the potato, carrot, pumpkin, apple, onion and tomato.", "Steam the vegetables and apple until very soft.", "Blend with a little butter into a smooth, mild curry.", "Serve over rice, or freeze in cubes for later."], tip: "Freeze in portion cubes for a quick mild curry any day.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7546219038435790098" } },
  { id: "pumpkin-chicken-rice", title: "Pumpkin Chicken Rice", emoji: "🎃", minMonths: 8, maxMonths: 99, prepMins: 20, servings: "Travel batch", texture: "Soft bite-sized", tags: ["Protein", "Veggie", "Chicken", "One-pan"], ingredients: ["Chicken", "Pumpkin", "Cooked rice", "Spring onion"], steps: ["Mince the chicken into small pieces.", "Cut the pumpkin into small cubes.", "Brown the chicken in a non-stick pan.", "Add pumpkin and cook until tender.", "Stir in cooked rice and combine.", "Pack into a thermos to keep warm for travel."], tip: "Travel-friendly — keep it warm in a food thermos for outings.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7548073639539789063" } },
  { id: "babys-first-birthday-smash-cake", title: "Baby's First Birthday Smash Cake", emoji: "🎂", minMonths: 10, maxMonths: 99, prepMins: 20, servings: "1 small cake", texture: "Soft bite-sized", tags: ["Egg", "Fruit", "No-cook"], ingredients: ["1 banana", "2 egg yolks", "Cake flour", "Raspberries", "Plain yogurt"], steps: ["Blend the banana with egg yolks until smooth.", "Whisk in cake flour to make a batter.", "Steam or pan-cook the batter into a soft cake.", "Spread plain yogurt over the cooled cake.", "Top with raspberries to decorate."], tip: "No oven needed — set the cake by steaming, then frost with plain yogurt.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7553639898914376967" } },
  { id: "banana-waffles", title: "Banana Waffles", emoji: "🧇", minMonths: 10, maxMonths: 99, prepMins: 15, servings: "2–3 baby portions", texture: "Soft finger food", tags: ["Egg", "Fruit", "Breakfast", "Finger-food"], ingredients: ["1 banana", "1 egg", "Yogurt", "Flour", "Blueberries"], steps: ["Mash the banana until smooth.", "Whisk in the egg and yogurt.", "Stir in flour to make a thick batter.", "Cook in a waffle maker until golden.", "Serve with blueberries on the side."], tip: "Cut waffles into strips for easy self-feeding.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7568112955338853640" } },
  { id: "prawn-mushroom-and-tofu-soup", title: "Prawn, Mushroom & Tofu Soup", emoji: "🍲", minMonths: 10, maxMonths: 99, prepMins: 20, servings: "1–2 baby portions", texture: "Soft bite-sized", tags: ["Protein", "Tofu", "Veggie", "Egg"], ingredients: ["Prawns", "Tofu", "Mixed mushrooms", "Carrot", "1 egg"], steps: ["Cut tofu into small cubes; dice the mushrooms and carrot.", "Scramble the egg, then set aside.", "Sauté the mushrooms, carrot and tofu.", "Add prawns and cook until pink.", "Add water for a light soup and simmer.", "Stir the egg back in and combine."], tip: "A quick one-pan soup with soft, gummable pieces.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7573678701662047495" } },
  { id: "pumpkin-chicken-gingerbread-bites", title: "Pumpkin Chicken Gingerbread Bites", emoji: "🍪", minMonths: 10, maxMonths: 99, prepMins: 30, servings: "2–3 baby portions", texture: "Soft finger food", tags: ["Protein", "Veggie", "Chicken", "Finger-food"], ingredients: ["Pumpkin", "Chicken", "Carrot", "Oats", "1 egg"], steps: ["Steam the pumpkin and carrot until soft.", "Mince the chicken finely.", "Mix pumpkin, carrot, chicken, oats and egg into a dough.", "Shape into small gingerbread-man figures.", "Bake or air-fry until set and cooked through."], tip: "Festive shapes that are soft enough for gums and fun for little hands.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7581840019980029191" } },
  { id: "waterless-chicken-and-napa-cabbage-soup", title: "Waterless Chicken & Napa Cabbage Soup", emoji: "🍲", minMonths: 10, maxMonths: 99, prepMins: 30, servings: "3–4 baby portions", texture: "Soft bite-sized", tags: ["Chicken", "One-pan", "Freezer-friendly", "Veggie"], ingredients: ["Napa cabbage", "Chicken", "Apple", "Onion", "Red dates", "1 cup water"], steps: ["Layer napa cabbage in the base of a pressure cooker.", "Add apple and onion for natural sweetness.", "Add chicken pieces and a few red dates.", "Pour in one cup of water.", "Pressure cook about 30 minutes.", "Shred the chicken before serving."], tip: "The cabbage, apple and onion release their own juices, so little added water is needed.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7600027362838826261" } },
  { id: "air-fryer-chicken-nuggets-and-fries", title: "Air-Fryer Chicken Nuggets & Fries", emoji: "🍗", minMonths: 12, maxMonths: 99, prepMins: 20, servings: "2–3 toddler portions", texture: "Soft finger food", tags: ["Chicken", "Protein", "Finger-food"], ingredients: ["Minced chicken", "Potatoes", "Cornstarch", "1 egg", "Onion"], steps: ["Cut potatoes into fries and steam until just soft.", "Mix minced chicken with finely chopped onion, egg and cornstarch, then shape into nuggets.", "Brush nuggets and fries lightly with oil.", "Air-fry until golden, flipping halfway.", "Cool and serve as a homemade happy meal."], tip: "A little oil before air-frying gives a crisp outside without deep-frying.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7603735610922208533" } },
  { id: "steamed-prawns-in-orange-cups", title: "Steamed Prawns in Orange Cups", emoji: "🍤", minMonths: 12, maxMonths: 99, prepMins: 20, servings: "2–3 toddler portions", texture: "Soft bite-sized", tags: ["Fish", "Protein", "One-pan"], ingredients: ["Prawns", "A little sesame oil", "1 orange", "Pumpkin", "Carrot", "Mixed-grain rice", "Sweetcorn"], steps: ["Marinate the prawns in a little sesame oil for 15 minutes.", "Halve and hollow the orange, reserving the cups.", "Steam the prawns until just cooked.", "Steam the pumpkin and carrot until soft.", "Serve the prawns in an orange cup with rice and corn."], tip: "Hollowed orange halves make fun, mess-free cups for a festive toddler meal.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7607451276674075924" } },
  { id: "rice-cooker-baby-meal-cubes", title: "Rice-Cooker Baby Meal Cubes", emoji: "🍚", minMonths: 10, maxMonths: 99, prepMins: 60, servings: "Multiple freezer cubes", texture: "Soft bite-sized", tags: ["Freezer-friendly", "One-pan", "Protein", "Veggie"], ingredients: ["Protein (salmon, chicken or beef)", "Mixed vegetables (carrot, pumpkin, peas, corn)", "Rice", "A little miso or tomato, for flavour"], steps: ["Choose a protein plus mixed veggies and rice for a balanced meal.", "Add everything to the rice cooker and cook together.", "Portion into a silicone cube tray and freeze.", "Reheat a cube at mealtime."], tip: "An hour on the weekend batch-cooks a week of freezer meal cubes.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7615983849905917204" } },
  { id: "grandmas-scallop-and-chickpea-congee", title: "Grandma's Scallop & Chickpea Congee", emoji: "🥣", minMonths: 8, maxMonths: 99, prepMins: 60, servings: "3–4 baby portions", texture: "Porridge / congee", tags: ["Protein", "Iron-rich", "Veggie"], ingredients: ["Rice", "Dried scallop", "Chickpeas", "Carrot", "Potato"], steps: ["Grate the carrot finely so it softens fully.", "Add rice, carrot, diced potato, chickpeas and rehydrated dried scallop to a pot.", "Pour in water and cook low and slow into a soft congee.", "Stir well and mash any larger pieces before serving."], tip: "Dried scallop adds gentle natural umami so no salt is needed.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7623777221525736724" } },
  { id: "apple-onion-water-sick-day-drink", title: "Apple Onion Water (Sick-Day Drink)", emoji: "🍎", minMonths: 8, maxMonths: 99, prepMins: 20, servings: "1–2 baby portions", texture: "Smooth purée", tags: ["Fruit", "No-cook", "Veggie"], ingredients: ["Apple", "Onion", "Shallot", "Water"], steps: ["Peel and roughly chop the apple, onion and shallot.", "Simmer gently in water until soft and fragrant.", "Strain and cool the liquid.", "Offer the warm apple-onion water to a baby with a cough or cold."], tip: "Naturally sweet from the apple — a gentle drink to soothe congestion without seasoning.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7628604487329959188" } },
  { id: "creamy-butter-prawn-udon", title: "Creamy Butter Prawn Udon", emoji: "🍜", minMonths: 12, maxMonths: 99, prepMins: 20, servings: "1–2 toddler portions", texture: "Soft bite-sized", tags: ["Fish", "Protein", "One-pan", "Dairy"], ingredients: ["Udon noodles", "Prawns", "Butter", "Milk or cream", "Carrot", "Cheese", "Garlic"], steps: ["Melt butter and cook chopped prawns until pink.", "Add finely chopped carrot and a little garlic, then soften.", "Add cooked udon to the pan.", "Pour in milk or cream and a little cheese, and toss until creamy.", "Cut the noodles short and cool before serving."], tip: "One pan, about 20 minutes — a quick creamy meal toddlers love.", source: { name: "Caryne Chua (TikTok)", url: "https://www.tiktok.com/@carynechua/video/7633055577622482197" } },

  // ---------- @feed.the.blob (Instagram) · Freezer meal prep ----------
  { id: "eat-up-beef-bolognese", title: "Eat Up Beef Bolognese", emoji: "🍝", minMonths: 8, maxMonths: 99, prepMins: 30, servings: "4–6 portions", texture: "Soft mince sauce (blend for 8–10m)", tags: ["Freezer-friendly", "Iron-rich", "Batch cook", "Family meal"], ingredients: ["2 stalks celery, diced", "1 medium carrot, diced", "1 medium onion, diced", "¼ cup dried red lentils, pre-soaked in boiling water 30 min", "250g beef (or any) mince", "250g canned whole tomatoes or tomato purée"], steps: ["Sauté the celery, carrot and onion over medium heat until soft (~5 min).", "Add the mince, breaking it up, and fry until thoroughly cooked (~10 min).", "Stir in the canned tomatoes and soaked red lentils until well combined; bring to a boil, then simmer 10 min.", "Cool, then freeze in portion cubes."], tip: "Red lentils add a quiet boost of protein, iron and fibre. 8–10m: blend to a purée. Steam 60ml cubes 15–20 min to reheat.", source: { name: "feed.the.blob (Instagram)", url: "https://www.instagram.com/feed.the.blob/" } },
  { id: "coco-loco-prawn-curry", title: "Coco Loco Prawn Curry", emoji: "🍛", minMonths: 12, maxMonths: 99, prepMins: 35, servings: "4 portions", texture: "Soft chopped", tags: ["Freezer-friendly", "Healthy fats", "Allergen: shellfish"], ingredients: ["½ stalk celery, diced", "½ medium carrot, diced", "½ medium onion, diced", "¼ cup sweet potato, diced", "12 medium prawns, chopped", "2 cloves garlic, minced", "200ml coconut milk + 200ml water", "1 tsp garlic powder", "1 tsp onion powder", "¼ tsp mild curry or turmeric powder"], steps: ["Fry the chopped prawns over medium heat until just pink, then set aside (~3 min).", "Sauté the onion and garlic until soft and translucent (~2 min).", "Add the sweet potato, celery and carrot and cook until slightly tender (~5 min).", "Stir in the garlic powder, onion powder and curry/turmeric and fry 30 sec.", "Pour in the coconut milk and water, bring to a boil, then simmer until the veg is soft (~10 min).", "Return the prawns to heat through (~2 min), then cool and freeze."], tip: "Shellfish is a common allergen — introduce on its own first. Naturally sweet and salt-free.", source: { name: "feed.the.blob (Instagram)", url: "https://www.instagram.com/feed.the.blob/" } },
  { id: "chicken-broth-for-the-soul", title: "Chicken Broth for the Soul", emoji: "🍲", minMonths: 6, maxMonths: 99, prepMins: 65, servings: "6–8 portions", texture: "Smooth broth", tags: ["Freezer-friendly", "Batch cook", "Singapore"], ingredients: ["1 stalk celery, roughly chopped", "1 medium carrot, roughly chopped", "1 onion, halved", "2 chicken carcasses", "1 inch ginger", "1 spring onion (white part)", "1 tbsp dried anchovies or dried shrimp", "1 tbsp dried soy beans (optional)"], steps: ["Blanch the bones in boiling water 3–5 min (or soak in cold water 1 hr), then rinse off any impurities.", "Put everything into a pressure cooker and add enough water to cover.", "Cook on high pressure for 1 hour.", "Strain the broth, cool, and freeze in cubes."], tip: "A no-salt flavour base — drop a cube into congee or purées. 6–10m: 15ml cubes.", source: { name: "feed.the.blob (Instagram)", url: "https://www.instagram.com/feed.the.blob/" } },
  { id: "red-lentil-potato-soup", title: "Red Lentil Potato Soup", emoji: "🥣", minMonths: 6, maxMonths: 99, prepMins: 35, servings: "4–6 portions", texture: "Soft soup (blend for 6–10m)", tags: ["Freezer-friendly", "Iron-rich", "Protein"], ingredients: ["2 tbsp olive oil", "1 stalk celery, diced", "1 medium carrot, diced", "1 onion, diced", "2 medium potatoes, diced", "½ cup red lentils, soaked in boiling water 30 min", "2 cups water or chicken broth"], steps: ["Heat the oil over medium heat.", "Add all the vegetables and sauté until tender and the onion is translucent.", "Stir in the soaked red lentils and water or broth.", "Bring to a boil, then cover and simmer on medium-low until the potatoes and lentils are tender (~15–20 min).", "Cool and freeze in portions."], tip: "Red lentils are soft and mild — an easy first legume. 6–10m: blend smooth; serve as-is from 12m.", source: { name: "feed.the.blob (Instagram)", url: "https://www.instagram.com/feed.the.blob/" } },
  { id: "cheesy-meatballs", title: "Cheesy Meatballs", emoji: "🧆", minMonths: 12, maxMonths: 99, prepMins: 35, servings: "15–18 balls", texture: "Soft finger food", tags: ["Freezer-friendly", "Protein", "Allergen: egg"], ingredients: ["2 stalks celery", "1 medium carrot", "1 medium onion", "1 egg", "250g pork (or any) mince", "½ cup panko breadcrumbs", "½–1 cup shredded mozzarella", "Optional: 1 tsp grated ginger, ¼ tsp garlic powder, ¼ tsp onion powder, 1 tsp low-sodium soy sauce"], steps: ["Blitz the celery, carrot and onion to a fine mirepoix.", "Cook the mirepoix in a pot over low heat for 5 min until softened, then cool slightly.", "Mix the mince, cooled mirepoix, mozzarella, egg, panko and any optional seasonings until well combined.", "Scoop tablespoon portions onto a baking tray and bake at 180°C for 20 min.", "Cool, then freeze."], tip: "Or freeze raw in 30/60ml moulds and air-fry at 180°C for 20 min (flip at 10 min).", source: { name: "feed.the.blob (Instagram)", url: "https://www.instagram.com/feed.the.blob/" } },
];

export function recipesForAge(ageMonths: number): Recipe[] {
  return RECIPES.filter((r) => r.minMonths <= ageMonths && ageMonths <= r.maxMonths);
}

/** Human age band, e.g. "6–10m" for bounded recipes or "8m+" for open-ended. */
export function ageBandLabel(r: Recipe): string {
  return r.maxMonths >= 99 ? `${r.minMonths}m+` : `${r.minMonths}–${r.maxMonths}m`;
}

export function recipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
