import type { AgeStage, Recipe } from "./types";

/**
 * Curated, age-staged baby & toddler recipe library.
 *
 * Method steps are written in our own words; ingredient lists are factual.
 * Each recipe links out to a reputable weaning source so you can read the
 * original and full safety guidance. Always follow your paediatrician's advice
 * on introducing allergens and on choking-hazard textures.
 *
 * Age filtering is band-based: a recipe shows only when the selected age falls
 * within [minMonths, maxMonths]. So smooth first-food purées drop off for older
 * babies — a 12-month-old won't be served 6-month purées.
 */

export const STAGES: AgeStage[] = [
  { id: "6m", label: "6 months", short: "6m", minMonths: 6, tone: "mint", blurb: "First tastes — smooth single-ingredient purées & soft steamed sticks." },
  { id: "8m", label: "8 months", short: "8m", minMonths: 8, tone: "butter", blurb: "Mashed combos & easy finger foods as she learns to self-feed." },
  { id: "10m", label: "10 months", short: "10m", minMonths: 10, tone: "peach", blurb: "More texture — soft lumps, mini meals and handheld bites." },
  { id: "12m", label: "12 months", short: "12m", minMonths: 12, tone: "lilac", blurb: "Toddler meals — family food, chopped small. (No more smooth purées.)" },
  { id: "18m", label: "18 months+", short: "18m+", minMonths: 18, tone: "coral", blurb: "Confident eater — bigger flavours and lunchbox ideas." },
];

const SRC = {
  nhs: { name: "NHS Start for Life", url: "https://www.nhs.uk/start-for-life/baby/weaning/recipes-and-meal-ideas/" },
  solidstarts: { name: "Solid Starts", url: "https://solidstarts.com/foods/" },
  bbc: { name: "BBC Good Food", url: "https://www.bbcgoodfood.com/recipes/collection/baby-and-toddler-recipes" },
  karmel: { name: "Annabel Karmel", url: "https://www.annabelkarmel.com/recipes/" },
  hlf: { name: "Healthy Little Foodies", url: "https://www.healthylittlefoodies.com/category/baby/" },
  hhFirstFood: { name: "HealthHub (HPB) — Baby’s First Food Journey", url: "https://www.healthhub.sg/live-healthy/babys_first_food_journey" },
  hhSolids: { name: "HealthHub (HPB) — Getting Ready for Solids", url: "https://www.healthhub.sg/well-being-and-lifestyle/pregnancy-and-infant-health/baby-getting-ready-for-solids" },
  hxWean: { name: "HealthXchange (SingHealth) — When & How to Wean", url: "https://www.healthxchange.sg/health-articles/baby-life-stages/baby-feeding/when-how-wean-baby" },
  hxGrowing: { name: "HealthXchange (SingHealth) — Top 10 Foods for the Growing Child", url: "https://www.healthxchange.sg/children/food-nutrition/foods-growing-child" },
  singhealth612: { name: "SingHealth — Early Childhood Nutrition 6–12 Months", url: "https://polyclinic.singhealth.com.sg/Documents/Early%20childhood%20nutrition%20from%206-12%20months.pdf" },
};

export const RECIPES: Recipe[] = [
  // ---------- 6 months+ ----------
  { id: "avocado-mash", title: "Creamy Avocado Mash", emoji: "🥑", minMonths: 6, maxMonths: 11, prepMins: 5, servings: "1 baby portion", texture: "Smooth mash", tags: ["No-cook", "Healthy fats", "4 ingredients or fewer"], ingredients: ["½ ripe avocado", "1–2 tsp breast milk or formula (to loosen)"], steps: ["Scoop the avocado flesh into a bowl.", "Mash with a fork until very smooth.", "Stir in a little milk to reach a soft, spoonable texture.", "Serve at room temperature straight away."], tip: "Avocado browns fast — make it just before serving.", source: SRC.solidstarts },
  { id: "sweet-potato-puree", title: "Sweet Potato Purée", emoji: "🍠", minMonths: 6, maxMonths: 10, prepMins: 20, servings: "3–4 portions", texture: "Smooth purée", tags: ["Freezer-friendly", "Veggie", "Batch cook"], ingredients: ["1 medium sweet potato, peeled & cubed", "Water or unsalted stock"], steps: ["Steam the sweet potato cubes for 12–15 min until very soft.", "Blend with a splash of the cooking water until silky.", "Cool to lukewarm and check the temperature before serving.", "Freeze extras in an ice-cube tray for quick meals."], tip: "Swap for butternut squash or carrot using the same method.", source: SRC.nhs },
  { id: "banana-mash", title: "Banana & Oat Mash", emoji: "🍌", minMonths: 6, maxMonths: 11, prepMins: 8, servings: "1 portion", texture: "Soft mash", tags: ["Breakfast", "No added sugar", "Quick"], ingredients: ["½ ripe banana", "1 tbsp baby porridge oats", "3 tbsp milk"], steps: ["Simmer the oats with milk for 3–4 min until soft and creamy.", "Mash the banana well and stir through.", "Loosen with a little extra milk if needed.", "Cool to warm before serving."], source: SRC.nhs },
  { id: "broccoli-trees", title: 'Steamed Broccoli "Trees"', emoji: "🥦", minMonths: 6, maxMonths: 24, prepMins: 12, servings: "2 portions", texture: "Soft finger food", tags: ["Baby-led", "Veggie", "First finger food"], ingredients: ["Broccoli florets with a long stalk to grip"], steps: ['Trim florets so each has a stalk "handle" for little hands.', "Steam for 8–10 min until soft enough to squash easily.", "Cool until just warm.", "Offer one floret at a time on the tray."], tip: "The floret head holds purées and sauces well for dipping later.", source: SRC.solidstarts },
  { id: "apple-pear-puree", title: "Apple & Pear Purée", emoji: "🍎", minMonths: 6, maxMonths: 10, prepMins: 18, servings: "4 portions", texture: "Smooth purée", tags: ["Fruit", "Freezer-friendly", "Batch cook"], ingredients: ["1 apple, peeled & chopped", "1 ripe pear, peeled & chopped", "Splash of water"], steps: ["Gently simmer the apple with a splash of water for 6–8 min.", "Add the pear and cook 2–3 min more until both are soft.", "Blend until smooth.", "Cool and serve, or freeze in cubes."], source: SRC.nhs },

  // ---------- 6 months+ · 🇸🇬 Singapore ----------
  { id: "sg-rice-cereal-veg", title: "Iron Rice Cereal with Veg Purée", emoji: "🍚", minMonths: 6, maxMonths: 10, prepMins: 10, servings: "1 portion", texture: "Smooth, slightly thicker than milk", tags: ["Singapore", "First food", "Iron-rich"], ingredients: ["2 tbsp iron-fortified baby rice cereal", "Breast milk or formula to mix", "1 tbsp pumpkin or carrot, steamed & puréed"], steps: ["Mix the rice cereal with warm milk to a smooth, runny paste.", "Stir in the steamed pumpkin or carrot purée for vitamins.", "Aim for a texture just thicker than milk so baby can lick it off the spoon.", "Introduce one new vegetable every 3–4 days."], tip: "HPB suggests iron-fortified cereal as a typical first food, with veg added for vitamin C to help iron absorption.", source: SRC.hhFirstFood },
  { id: "sg-papaya-banana", title: "Papaya & Banana Scrape", emoji: "🥭", minMonths: 6, maxMonths: 11, prepMins: 5, servings: "1 portion", texture: "Smooth mash", tags: ["Singapore", "No-cook", "Fruit"], ingredients: ["A wedge of ripe papaya", "½ ripe banana"], steps: ["Scrape the soft papaya flesh with a spoon into a bowl.", "Mash the banana and combine.", "Mix to a smooth, lump-free purée.", "Serve fresh — no added sugar needed."], tip: "SingHealth lists banana and papaya among soft, ripe local fruit ideal for scraping or mashing.", source: SRC.hxWean },
  { id: "sg-sweetpotato-congee", title: "Sweet Potato Brown-Rice Congee", emoji: "🥣", minMonths: 6, maxMonths: 18, prepMins: 35, servings: "3 portions", texture: "Soft, smooth congee", tags: ["Singapore", "Batch cook", "Veggie"], ingredients: ["3 tbsp white or brown rice, rinsed", "1 small sweet potato, diced", "2 cups water or unsalted stock"], steps: ["Simmer the rice with water until it breaks down into soft congee (~25–30 min).", "Add the sweet potato partway and cook until very soft.", "Blend or mash to the texture your baby is ready for.", "Cool to warm; freeze extra portions."], tip: "A classic local first congee — SingHealth suggests blended home-cooked rice porridge with mashed vegetables.", source: SRC.hxWean },

  // ---------- 8 months+ ----------
  { id: "lentil-veg-mash", title: "Red Lentil & Veg Mash", emoji: "🍲", minMonths: 8, maxMonths: 24, prepMins: 25, servings: "3 portions", texture: "Soft mash with lumps", tags: ["Iron-rich", "Protein", "Freezer-friendly"], ingredients: ["3 tbsp red lentils, rinsed", "1 small carrot, diced", "¼ onion, finely chopped", "1 tsp olive oil", "200ml unsalted stock or water"], steps: ["Soften the onion and carrot in the oil for 3–4 min.", "Add the lentils and stock, then simmer 18–20 min until very soft.", "Mash to a soft, lumpy texture (or blend for younger babies).", "Cool to warm before serving."], tip: "Iron from lentils absorbs better served with veg like this.", source: SRC.karmel },
  { id: "salmon-sweetpotato", title: "Salmon & Sweet Potato Mash", emoji: "🐟", minMonths: 8, maxMonths: 24, prepMins: 22, servings: "2 portions", texture: "Soft mash", tags: ["Omega-3", "Protein", "Allergen: fish"], ingredients: ["1 small skinless salmon fillet", "1 small sweet potato, cubed", "1 tbsp full-fat cream cheese or milk"], steps: ["Steam the sweet potato 12–15 min until soft.", "Add the salmon for the last 8 min until cooked through and flaking.", "Flake the salmon carefully, checking for any bones.", "Mash everything with the cream cheese until smooth and soft."], tip: "Introduce fish on its own first to watch for any reaction.", source: SRC.karmel },
  { id: "cheesy-scrambled-egg", title: "Soft Cheesy Scrambled Egg", emoji: "🍳", minMonths: 8, maxMonths: 99, prepMins: 8, servings: "1 portion", texture: "Soft curds", tags: ["Protein", "Breakfast", "Allergen: egg"], ingredients: ["1 egg", "1 tbsp milk", "1 tbsp grated mild cheese", "Knob of unsalted butter"], steps: ["Whisk the egg with the milk.", "Melt the butter in a pan on low heat.", "Add the egg and stir gently into soft curds — do not let it brown.", "Stir in the cheese off the heat and cool before serving."], tip: "Cook eggs until fully set for babies.", source: SRC.hlf },
  { id: "banana-oat-pancakes", title: "2-Ingredient Banana Pancakes", emoji: "🥞", minMonths: 8, maxMonths: 99, prepMins: 12, servings: "6 mini pancakes", texture: "Soft finger food", tags: ["Baby-led", "No added sugar", "Allergen: egg"], ingredients: ["1 ripe banana", "1 egg", "A little butter or oil for the pan"], steps: ["Mash the banana smooth, then whisk in the egg.", "Heat a lightly greased non-stick pan on low.", "Spoon small rounds and cook 1–2 min each side until set.", "Cool and cut into strips for little hands."], source: SRC.hlf },
  { id: "veggie-fritters", title: "Soft Courgette & Cheese Fritters", emoji: "🧆", minMonths: 8, maxMonths: 99, prepMins: 18, servings: "8 fritters", texture: "Soft finger food", tags: ["Baby-led", "Veggie", "Freezer-friendly"], ingredients: ["1 small courgette, grated & squeezed dry", "3 tbsp grated cheese", "1 egg", "3 tbsp flour"], steps: ["Mix the courgette, cheese, egg and flour into a thick batter.", "Heat a little oil in a non-stick pan on medium-low.", "Cook small spoonfuls 2 min each side until golden and set.", "Drain, cool and serve in baby-fist-sized strips."], source: SRC.bbc },

  // ---------- 8 months+ · 🇸🇬 Singapore ----------
  { id: "sg-fish-spinach-porridge", title: "Fish & Spinach Porridge", emoji: "🐠", minMonths: 8, maxMonths: 24, prepMins: 35, servings: "2 portions", texture: "Soft porridge, finely flaked", tags: ["Singapore", "Protein", "Allergen: fish"], ingredients: ["3 tbsp rice, rinsed", "2 cups water or unsalted stock", "A small piece of soft white fish (e.g. cod / threadfin)", "A few spinach leaves, finely chopped"], steps: ["Simmer the rice into a soft porridge (~25–30 min).", "Add the fish and cook until it flakes easily; check carefully for bones.", "Stir in the chopped spinach for the last 2 min.", "Mash to a soft, lump-suitable texture; cool to warm. No added salt."], tip: "SingHealth recommends finely flaked fish as a soft protein from around 7–8 months.", source: SRC.singhealth612 },
  { id: "sg-tofu-pumpkin", title: "Silken Tofu with Steamed Pumpkin", emoji: "🧈", minMonths: 8, maxMonths: 24, prepMins: 15, servings: "2 portions", texture: "Soft mash", tags: ["Singapore", "Plant protein", "Allergen: soy"], ingredients: ["½ block soft silken tofu", "A wedge of pumpkin, cubed"], steps: ["Steam the pumpkin 10–12 min until very soft.", "Warm the silken tofu briefly (steam or blanch).", "Mash the pumpkin and tofu together until smooth and soft.", "Serve warm — a gentle, iron- and protein-friendly local staple."], tip: "HPB lists soybean curd (tofu) among soft, protein-rich first foods.", source: SRC.hhSolids },

  // ---------- 10 months+ ----------
  { id: "mini-meatballs", title: "Soft Chicken Mini Meatballs", emoji: "🍖", minMonths: 10, maxMonths: 99, prepMins: 25, servings: "12 small meatballs", texture: "Soft chopped", tags: ["Protein", "Iron-rich", "Freezer-friendly"], ingredients: ["150g chicken or turkey mince", "2 tbsp soft breadcrumbs", "1 tbsp grated apple or courgette", "1 tsp dried herbs"], steps: ["Mix everything and roll into small, soft meatballs.", "Brown gently in a little oil, then add a splash of water.", "Cover and steam-cook 8–10 min until cooked through.", "Cool, then quarter for younger eaters."], tip: "Simmer in a no-salt tomato sauce to serve with pasta.", source: SRC.karmel },
  { id: "pasta-tomato", title: "Hidden-Veg Tomato Pasta", emoji: "🍝", minMonths: 10, maxMonths: 99, prepMins: 22, servings: "3 portions", texture: "Soft chopped", tags: ["Veggie", "Batch cook", "Family meal"], ingredients: ["Small pasta shapes (e.g. macaroni)", "1 carrot + ½ courgette, grated", "1 tin chopped tomatoes (no salt)", "1 tsp olive oil", "Grated cheese to finish"], steps: ["Soften the grated veg in the oil for 5 min.", "Add the tomatoes and simmer 12 min until thick.", "Blend smooth if you like, then toss with cooked pasta.", "Stir in cheese and cool to warm before serving."], source: SRC.bbc },
  { id: "fish-cakes", title: "Mini Salmon Fish Cakes", emoji: "🐠", minMonths: 10, maxMonths: 99, prepMins: 28, servings: "8 small cakes", texture: "Soft finger food", tags: ["Omega-3", "Baby-led", "Allergen: fish"], ingredients: ["1 cooked salmon fillet, flaked", "1 small potato, boiled & mashed", "2 tbsp sweetcorn or peas", "1 tbsp flour for shaping"], steps: ["Mix the salmon, mash and veg; check for bones.", "Shape into small patties and dust lightly with flour.", "Pan-fry in a little oil 2–3 min each side until golden.", "Cool and cut into strips."], source: SRC.karmel },
  { id: "porridge-fingers", title: "Baked Oat Porridge Fingers", emoji: "🌾", minMonths: 10, maxMonths: 99, prepMins: 30, servings: "10 fingers", texture: "Soft finger food", tags: ["Breakfast", "No added sugar", "Freezer-friendly"], ingredients: ["1 cup oats", "1 mashed banana", "1 cup milk", "1 egg", "Handful blueberries"], steps: ["Mix everything into a loose batter and pour into a lined tin.", "Bake at 180°C for 20–25 min until set and golden.", "Cool fully, then slice into grabbable fingers.", "Great warm or cold; freezes well."], source: SRC.hlf },
  { id: "sg-chicken-carrot-congee", title: "Minced Chicken & Carrot Congee", emoji: "🍜", minMonths: 10, maxMonths: 99, prepMins: 35, servings: "3 portions", texture: "Soft congee with fine lumps", tags: ["Singapore", "Protein", "Family meal"], ingredients: ["4 tbsp rice, rinsed", "2½ cups water or unsalted stock", "2 tbsp minced chicken", "1 small carrot, finely diced"], steps: ["Simmer the rice and carrot into a soft congee (~25 min).", "Stir in the minced chicken and cook until fully done.", "Mash any lumps to a texture your baby can manage.", "Cool to warm; season for adults separately, not for baby."], tip: "An everyday local porridge — SingHealth suggests minced meat added to rice porridge as texture develops.", source: SRC.singhealth612 },

  // ---------- 12 months+ ----------
  { id: "veg-omelette", title: "Cheese & Veg Omelette Bites", emoji: "🧀", minMonths: 12, maxMonths: 99, prepMins: 15, servings: "6 bites", texture: "Soft finger food", tags: ["Protein", "Veggie", "Allergen: egg"], ingredients: ["2 eggs", "2 tbsp grated cheese", "3 tbsp finely chopped cooked veg", "Knob of butter"], steps: ["Whisk the eggs with the cheese and veg.", "Pour into a greased muffin tin or small pan.", "Bake at 180°C for 12–14 min (or pan-cook) until set.", "Cool and cut into toddler-sized squares."], source: SRC.hlf },
  { id: "chicken-veg-curry", title: "Mild Chicken & Coconut Curry", emoji: "🍛", minMonths: 12, maxMonths: 99, prepMins: 30, servings: "3 portions", texture: "Soft chopped", tags: ["Protein", "Family meal", "Batch cook"], ingredients: ["1 chicken breast, diced small", "½ onion + 1 carrot, finely chopped", "½ tsp mild curry powder", "150ml coconut milk", "Cooked rice to serve"], steps: ["Soften the onion and carrot, then stir in the curry powder.", "Add the chicken and brown for 3–4 min.", "Pour in the coconut milk and simmer 12–15 min until tender.", "Chop any large pieces small and serve over soft rice."], tip: "Keep it salt-free; let adults season their own bowls.", source: SRC.karmel },
  { id: "pita-pizza", title: "Mini Pita Pizzas", emoji: "🍕", minMonths: 12, maxMonths: 99, prepMins: 15, servings: "2 pizzas", texture: "Soft finger food", tags: ["Quick", "Veggie", "Family meal"], ingredients: ["1 wholemeal pita or muffin", "2 tbsp no-salt tomato sauce", "Grated mozzarella", "Finely chopped soft veg toppings"], steps: ["Spread the tomato sauce over the pita base.", "Scatter cheese and soft veg on top.", "Bake at 190°C for 8–10 min until the cheese melts.", "Cool and cut into small wedges or strips."], source: SRC.bbc },
  { id: "sg-steamed-egg", title: "Silky Steamed Egg with Fish", emoji: "🥚", minMonths: 12, maxMonths: 99, prepMins: 18, servings: "2 portions", texture: "Silky soft custard", tags: ["Singapore", "Protein", "Allergen: egg, fish"], ingredients: ["1 egg", "80ml unsalted stock or water", "1 tbsp finely flaked cooked fish", "A few peas or chopped soft veg"], steps: ["Whisk the egg with the stock and strain for a smooth custard.", "Stir in the flaked fish and soft veg in a heatproof bowl.", "Steam on low 10–12 min until just set and silky.", "Cool to warm; serve with soft rice."], tip: "HealthXchange lists egg and fish among top foods for growing children — steam until fully set.", source: SRC.hxGrowing },

  // ---------- 18 months+ ----------
  { id: "veggie-muffins", title: "Savoury Veggie Muffins", emoji: "🧁", minMonths: 18, maxMonths: 99, prepMins: 30, servings: "12 mini muffins", texture: "Soft handheld", tags: ["Lunchbox", "Veggie", "Freezer-friendly"], ingredients: ["1½ cups self-raising flour", "1 grated carrot + handful sweetcorn", "½ cup grated cheese", "1 egg + ¾ cup milk", "3 tbsp oil"], steps: ["Mix the wet ingredients, then fold in the dry ingredients and veg.", "Spoon into a mini-muffin tin.", "Bake at 180°C for 18–20 min until risen and golden.", "Cool fully; great in lunchboxes or as a snack."], source: SRC.hlf },
  { id: "pasta-salad", title: "Toddler Pasta Salad Cups", emoji: "🥗", minMonths: 18, maxMonths: 99, prepMins: 18, servings: "3 portions", texture: "Soft chopped", tags: ["Lunchbox", "No-cook assembly", "Veggie"], ingredients: ["Cooked small pasta", "Soft cherry tomatoes, quartered", "Cucumber, diced small", "Cubes of mild cheese", "1 tsp olive oil"], steps: ["Cool the cooked pasta under cold water and drain.", "Quarter the tomatoes and finely dice the other veg.", "Toss everything with a little olive oil.", "Serve cool — perfect for picnics and lunchboxes."], tip: "Always quarter grapes and tomatoes to reduce choking risk.", source: SRC.bbc },
  { id: "sweet-potato-chili", title: "Mild Beef & Sweet Potato Chilli", emoji: "🫘", minMonths: 18, maxMonths: 99, prepMins: 35, servings: "4 portions", texture: "Soft chopped", tags: ["Iron-rich", "Family meal", "Batch cook"], ingredients: ["250g lean beef mince", "1 sweet potato, diced small", "½ tin kidney beans, rinsed & mashed", "1 tin chopped tomatoes (no salt)", "½ tsp mild paprika"], steps: ["Brown the mince, then add the sweet potato and paprika.", "Stir in the tomatoes and beans.", "Simmer 20–25 min until the sweet potato is tender.", "Mash any firm pieces and serve with rice or soft tortilla."], tip: "Mash the beans so they are not a choking hazard.", source: SRC.karmel },
];

/** Band filter: recipe shows only when ageMonths is within [minMonths, maxMonths]. */
export function recipesForAge(ageMonths: number): Recipe[] {
  return RECIPES.filter((r) => r.minMonths <= ageMonths && ageMonths <= r.maxMonths);
}

/** Human age band, e.g. "6–10m" for bounded recipes or "8m+" for open-ended. */
export function ageBandLabel(r: Recipe): string {
  return r.maxMonths >= 99 ? `${r.minMonths}m+` : `${r.minMonths}–${r.maxMonths}m`;
}

export function recipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
